---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu ansible nodes
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family =="debian"