---
# tasks file for mywebrole

- name: install webserver
  apt:
    name: apache2
    state: present
    notify: restartwebserver

- name: copy index file into node side
  template:
       src: templates/myindex.j2
       dest: /var/www/html/index.html
       notify: restartwebserver